### ISSUE TITLE
r2rml / rml

### ISSUE THREAD

**Issue by akuckartz** [tmdt-buw/plasma#2]
How could [r2rml](https://www.w3.org/TR/r2rml/) or [rml](https://rml.io/) mapping be integrated?

**Comment by saiyee** [comment]
Currently, there is no integrated support for (R2)RML in PLASMA. This is planned be added in the future and will support both import (RML mapping -> PLASMA mapping) as well as export (PLASMA -> RML) to increase compatibility with other frameworks/editors.
However, I cannot give a specific timeline for when this will happen.
